% SCENEGEN_DEMO Demo showing the 3D scene generated by scenegen
% CMP Vision Algorithms http://visionbook.felk.cvut.cz
% Tomas Svoboda, 2006-2007

% $Id: scenegen_demo_decor.m 1074 2007-08-14 09:45:42Z kybic $


outdir = './output_images/'; 
if ~(exist(outdir)==7)
  mkdir(outdir)
end

scenename = 'house';
[X,L] = scenegen(scenename);
X(4,:) = 1;

fig = display3Dscene([],X,L)

campos([5,5,5])
print('-depsc',[outdir,'3D_scene.eps'])


